name: Unit test
on: push

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout code
        uses : actions/checkout@v3
      
      - name : Install Packages 
        run : python pip -m install unittest .
      
      - name : Run tests 
        run : unittest test01.py